services:
  gateway:
    build: .
    container_name: gateway
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - dist-sys-ms-network

networks:
  dist-sys-ms-network:
    external: true
