spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 50000
                response-timeout: 50s
            default-filters:
                - name:
                    args:
                        retries: 3
                        methods: GET,POST,PUT,DELETE
                        statuses: BAD_GATEWAY
                        backoff:
                            firstBackoff: 10ms
                            maxBackoff: 50ms
                            factor: 2
                            basedOnPreviousValue: false
        config:
            discovery:
                enabled: true
                service-id: config
            request-connected-timeout: 5000
            request-read-timeout: 5000
            fail-fast: true
            retry:
                max-attempts: 10
                initial-interval: 2000
                max-interval: 10000
                multiplier: 1.5
    config:
        import: "optional:configserver:"

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
    instance:
        prefer-ip-address: true
