spring:
    application:
        name: gateway
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 50000
                response-timeout: 50s
            default-filters:
                - name:
                    args:
                        retries: 3
                        methods: GET,POST
                        statuses: BAD_GATEWAY
                        backoff:
                            firstBackoff: 10ms
                            maxBackoff: 50ms
                            factor: 2
                            basedOnPreviousValue: false
    config:
        import: "optional:configserver:"

server:
    port: ${SERVER_PORT:8080}

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
    tracing:
        enabled: true
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
